apiVersion: v1
kind: Secret
metadata:
  name: devops-api-secret
  namespace: devops-backend
  labels:
    app.kubernetes.io/name: devops-api
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DB_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
