apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yml
  - 02-configmap.yml
  - 03-secret.yml
  - 04-init-db-job.yml
  - 05-backend-deployment.yml
  - 06-backend-service.yml
  - 07-backend-ingress.yml
  - 08-backend-hpa.yml
images:
  - name: ghcr.io/martin-domenech/proyecto-final-devops
    newTag: latest
